### ISSUE TITLE
Lab Report 4 Feedback

### ISSUE THREAD

**Issue by pramithready** [minaiie/cse15l-lab-reports#4]
Here is your feedback for Lab Report 4:

- [x] Provides link to their markdown-parse repository 
- [x] Provides link to the markdown-parse repository they reviewed

Snippet 1

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 2

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Snippet 3

- [x] Shows the test(s) / expected output in MarkdownParseTest.java
- [x] Shows the output of running test(s) for their implementation 
- [x] Shows the output of running for the implementation they reviewed
- [x] Answers the code change question about their program

Additional comments from your grader:
Nice job, but we want your lab reports to be a web page on your personal Github Pages site. Please make this report a web page on your personal site and resubmit to get full credit.

Feel free to comment below any questions about the rubric/feedback

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by minaiie** [comment]
Sorry, I am little unclear about how to make the lab reports into  a web page on your personal Github Pages site. I think this is already on my personal Github Pages site, should I turn it into a webpage or something? It would be great help if you can specify or give more specific steps for me to follow!

**Comment by pramithready** [comment]
In Lab 2, we went over making a personal Github Pages site, with separate web pages. You provided a direct link to this report in your Github repository, but we wanted to see your report as a web page on your Github Pages site, not as a file in your Github repository. Take a look at the steps in Lab 2 to make the site, and if you need more direct help, please feel free to ask here or at office hours!

https://ucsd-cse15l-w22.github.io/week/week2/#making-a-pages-site

**Comment by minaiie** [comment]
Thanks for your help! I am now able to have the page, but it seems that all images in my page becomes unavailable. Do you have any idea of this issue? https://minaiie.github.io/cse15l-lab-reports/Lab%20Report%204.html.

**Comment by pramithready** [comment]
Looks good! You could try to use the local path to the screenshots instead of using a URL in your markdown.
